export const PERSON_GET_REQUEST_BEGIN = 'PERSON_GET_REQUEST_BEGIN'
export const PERSON_GET_REQUEST_SUCCESS = 'PERSON_GET_REQUEST_SUCCESS'
export const PERSON_GET_REQUEST_ERROR = 'PERSON_GET_REQUEST_ERROR'